### ISSUE TITLE
[Suggestion] Modify 180-degree spins to better match Nullpomino

### ISSUE THREAD

**Issue by Frostplays-ZERO** [jezevec10/jstris-guide#12]
I don't know what the kick tables are for 180-spins, but things that are possible in Nullpo aren't possible in JSTris.

**Comment by jezevec10** [comment]
Thanks for the suggestion. It is not specific to the jstris-guide document, therefore closing it.

I can recommend posting another suggestions to the jstris discord (https://discord.gg/RcNFCZC), which has #ideas channel.
