### ISSUE TITLE
API to get play data

### ISSUE THREAD

**Issue by kjaymiller** [jezevec10/jstris-guide#28]
I see there are stats being recorded about your gameplay. Is it possible to get access to personal stats. 

If not my feature request would be to access the information via REST API, GraphQL, or during play via a webhook where stats are sent after each drop.

My goal is to gather information at a level that most people won't care about. This is 100% for research and to present on as a demo of how to stream interesting data and learn from your games.

**Comment by jezevec10** [comment]
Hi, the API for getting user stats is documented here

https://erickmack.github.io/JstrisAPIdocs/

Check if it contains some of the info you need,

**Comment by kjaymiller** [comment]
It gives some good stat information that we could record over time, but not necessarily the in-game data.

The idea is to be able to show some board states during the game. We weren't sure what would be available butI think we can look at what we can get from this API. I would definitely like to see it expanded to show more but I understand that it's not something that is just easily added.

**Comment by g-rar** [comment]
Not entirely sure if the page is still available. Can't find it using google either. Did the page go down?

**Comment by jezevec10** [comment]
Moved here
https://jezevec10.github.io/jstris-api-docs/
